## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [4]:
# Create a list of at least 10 column names to use as X data
# Create X_df using your selected columns
X_df = attrition_df[['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'PercentSalaryHike', 'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']]

# Show the data types for X_df
print(X_df.dtypes)

Education                  int64
Age                        int64
DistanceFromHome           int64
JobSatisfaction            int64
PercentSalaryHike          int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
dtype: object


In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.3, random_state=42)

In [6]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
for col in X_df.select_dtypes(include=['object']).columns:
    X_df[col] = pd.to_numeric(X_df[col], errors='coerce')
X_df = X_df.convert_dtypes()

In [7]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
# Create a OneHotEncoder for the Department column
department_train = y_train['Department']
department_test = y_test['Department']
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
encoder.fit(department_train.values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
department_train_encoded = encoder.transform(department_train.values.reshape(-1, 1))
department_test_encoded = encoder.transform(department_test.values.reshape(-1, 1))

# Print arrays
print("Encoded Training Data:")
print(department_train_encoded)
print("Encoded Testing Data:")
print(department_test_encoded)

Encoded Training Data:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Encoded Testing Data:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [9]:
# Create a OneHotEncoder for the Attrition column
attrition_train = y_train['Attrition']
attrition_test = y_test['Attrition']
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
encoder.fit(attrition_train.values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
attrition_train_encoded = encoder.transform(attrition_train.values.reshape(-1, 1))
attrition_test_encoded = encoder.transform(attrition_test.values.reshape(-1, 1))
train_subset = np.concatenate((attrition_train_encoded[:2], attrition_train_encoded[-2:]))
test_subset = np.concatenate((attrition_test_encoded[:2], attrition_test_encoded[-2:]))

# Print arrays
print("Encoded Training Data:")
print(np.array2string(train_subset, separator=', ', prefix='array([', suffix='])'))
print("Encoded Testing Data:")
print(np.array2string(test_subset, separator=', ', prefix='array([', suffix='])'))

Encoded Training Data:
[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]
Encoded Testing Data:
[[1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]]


## Create, Compile, and Train the Model

In [25]:
# Find the number of columns in the X training data
input_shape = X_train_scaled.shape[1]

# Create the input layer
inputs = Input(shape=(input_shape,))

# Create at least two shared layers
shared_layer_1 = Dense(64, activation='relu', name='shared1')(inputs)
shared_layer_2 = Dense(128, activation='relu', name='shared2')(shared_layer_1)
# shared_layer_3 = Dense(64, activation = 'relu')(shared_layer_2)
# shared_layer_4 = Dense(64, activation = 'relu')(shared_layer_3)
# shared_layer_5 = Dense(3, activation = 'relu')(shared_layer_4)
# shared_layer_6 = Dense(2, activation = 'relu')(shared_layer_5)

In [26]:
# Create a branch for Department
# with a hidden layer and an output layer
department = attrition_df['Department'].nunique()

# Create the hidden layer
department_hidden_layer = Dense(32, activation='relu', name='department_hidden')(shared_layer_2)

# Create the output layer
# department_output_layer = Dense(3, department, activation='softmax', name='department_output')(department_hidden_layer)
department_output_layer = Dense(5, activation='softmax', name='department_output')(department_hidden_layer)

In [27]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
attrition_hidden_layer = Dense(32, activation='relu', name='attrition_hidden')(shared_layer_2)

# Create the output layer
attrition_output_layer = Dense(1, activation='sigmoid', name='attrition_output')(attrition_hidden_layer)

In [28]:
# Create the model
model = Model(inputs=inputs, outputs=[department_output_layer, attrition_output_layer], name="model")


# Compile the model
# model.compile(optimizer=Adam(), loss=['categorical_crossentropy', 'binary_crossentropy'], metrics=['accuracy'])
model.compile(optimizer='adam', loss=['categorical_crossentropy', 'binary_crossentropy'], metrics=['accuracy'])




# Summarize the model
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_2 (InputLayer)        [(None, 10)]                 0         []                            
                                                                                                  
 shared1 (Dense)             (None, 64)                   704       ['input_2[0][0]']             
                                                                                                  
 shared2 (Dense)             (None, 128)                  8320      ['shared1[0][0]']             
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared2[0][0]']             
                                                                                              

In [31]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Assuming y_train and y_test are your target labels for training and testing data
# and they are in a format that LabelEncoder can handle (e.g., a Series of strings)

# Create a label encoder object
encoder = LabelEncoder()

# Convert y_train and y_test to a 1-dimensional array if they are not already
y_train_1d = y_train.values.ravel() if y_train.ndim > 1 else y_train.values
y_test_1d = y_test.values.ravel() if y_test.ndim > 1 else y_test.values

# Fit the encoder to the training data and transform both the training and testing data
y_train_encoded = encoder.fit_transform(y_train_1d)
y_test_encoded = encoder.transform(y_test_1d)

# Now, convert the numeric labels to one-hot encoded format
y_train_one_hot = to_categorical(y_train_encoded, num_classes=5)
y_test_one_hot = to_categorical(y_test_encoded, num_classes=5)

In [33]:
# from sklearn.preprocessing import LabelEncoder
# from tensorflow.keras.utils import to_categorical

# # Create a label encoder object
# encoder = LabelEncoder()

# # Fit the encoder to the training data and transform both the training and testing data
# y_train_encoded = encoder.fit_transform(y_train)
# y_test_encoded = encoder.transform(y_test)

# # Now, convert the numeric labels to one-hot encoded format
# y_train_one_hot = to_categorical(y_train_encoded, num_classes=5)
# y_test_one_hot = to_categorical(y_test_encoded, num_classes=5)

In [34]:
# encoder = OneHotEncoder(sparse_output=False)
# y_train_encoded = encoder.fit_transform(y_train.values.reshape(-1, 1))
# y_test_encoded = encoder.transform(y_test.values.reshape(-1, 1))

In [36]:
# # Assuming department_output_layer is your model's output layer for the "Department" prediction
# # Check the number of output units in the department_output_layer
# num_output_units = department_output_layer.shape[1]

# # Check the number of classes in your one-hot encoded target labels
# num_classes = y_train_encoded.shape[1]

# print(f"Number of output units in the model: {num_output_units}")
# print(f"Number of classes in the target labels: {num_classes}")

In [37]:
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)


Shape of y_train: (1029, 2)
Shape of y_test: (441, 2)


In [39]:
# from sklearn.preprocessing import LabelEncoder
# from tensorflow.keras.utils import to_categorical

# # Create a label encoder object
# encoder = LabelEncoder()

# # Fit the encoder to the training data and transform both the training and testing data
# y_train_encoded = encoder.fit_transform(y_train)
# y_test_encoded = encoder.transform(y_test)

# # Now, convert the numeric labels to one-hot encoded format
# y_train_one_hot = to_categorical(y_train_encoded, num_classes=5)
# y_test_one_hot = to_categorical(y_test_encoded, num_classes=5)

In [43]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Create a label encoder object
encoder = LabelEncoder()

# Fit the encoder to the training data and transform both the training and testing data
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

# Now, convert the numeric labels to one-hot encoded format
y_train_one_hot = to_categorical(y_train_encoded, num_classes=5)
y_test_one_hot = to_categorical(y_test_encoded, num_classes=5)

ValueError: y should be a 1d array, got an array of shape (1029, 2) instead.

In [42]:
from tensorflow.keras.utils import to_categorical

# Assuming y_train and y_test are your target labels for training and testing data
# Convert y_train and y_test to one-hot encoded format
y_train_encoded = to_categorical(y_train, num_classes=5)
y_test_encoded = to_categorical(y_test, num_classes=5)

# Now, y_train_encoded and y_test_encoded are one-hot encoded versions of your target labels

ValueError: invalid literal for int() with base 10: 'No'

In [41]:
# Train the model
history = model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/10


ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1151, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1209, in compute_loss
        return self.compiled_loss(
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/losses.py", line 2221, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/usr/local/lib/python3.10/dist-packages/keras/src/backend.py", line 5573, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 2) and (None, 5) are incompatible


In [21]:
# Evaluate the model with the testing data


In [20]:
# Print the accuracy for both department and attrition


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.